// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskMgmt.Data;

#nullable disable

namespace TaskMgmt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517114859_SeedDefaultTasks")]
    partial class SeedDefaultTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("TaskMgmt.Model.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Create folders and configure dependencies.",
                            IsCompleted = true,
                            Title = "Set up project structure"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Plan tables, relationships and migrations.",
                            IsCompleted = true,
                            Title = "Design database schema"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Implement GET, POST, PUT, DELETE for tasks.",
                            IsCompleted = false,
                            Title = "Build REST API endpoints"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Connect UI to the API and handle responses.",
                            IsCompleted = false,
                            Title = "Integrate Angular frontend"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Configure hosting and set up CI/CD pipeline.",
                            IsCompleted = false,
                            Title = "Deploy to production"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
